{% set name = "torchkin" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchkin-{{ version }}.tar.gz
  sha256: 42676bcbc08111e1fb3ac13376ca73ed0e5df0bec1fb3d48239a08006b4f4719

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - urdfdom-py
    - torchlie

test:
  imports:
    - torchkin

about:
  home: https://github.com/facebookresearch/theseus/lie
  summary: Torch extension for differentiable kinematics.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
